spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: david
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

  main:
    web-application-type: servlet

server:
  port: 8080
